# Generated by Django 4.2.13 on 2024-05-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("content", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type_of_people",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "number_of_people",
                    models.IntegerField(blank=True, max_length=500, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("enroll_start_date", models.DateField(blank=True, null=True)),
                ("enroll_end_date", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("content_link", models.URLField(default="")),
            ],
        ),
    ]
