# Generated by Django 4.2.13 on 2024-05-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_rename_name_content_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="태그명"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="content",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="contents.hashtag",
                verbose_name="해시태그 목록",
            ),
        ),
    ]
