# Generated by Django 4.2.13 on 2024-05-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0003_hashtag_content_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="search_count",
            field=models.IntegerField(default=0),
        ),
    ]
