# Generated by Django 4.2.13 on 2024-05-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0004_content_search_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="eduW",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="etc",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="how",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="money",
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="content",
            name="week",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
