# Generated by Django 4.2.13 on 2024-05-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contents",
            "0005_content_eduw_content_etc_content_how_content_money_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="end_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="enroll_end_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="enroll_start_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="money",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="content",
            name="start_date",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
